### ISSUE TITLE
Question wrt Debian packaging

### ISSUE THREAD

**Issue by pombredanne** [ardumont/fossology-nomossa#1]
Hi

I was not sure how to best contact you. Since you have some experience in Debian packaging and are interested in license detection, I am looking for hints on how to best package https://github.com/nexB/scancode-toolkit/ for Debian...
Can I find you on IRC?

--
Thanks!

**Comment by ardumont** [comment]
Hello,

> I was not sure how to best contact you.

Well, that's one way to do it :D

>  Since you have some experience in Debian packaging and are interested in license detection, I am looking for hints on how to best package https://github.com/nexB/scancode-toolkit/ for Debian...

Well, it's not really a simple subject...

I was hinted at https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.en.pdf
multiple times which i read multiple times as well. I also read multiple times some part of https://www.debian.org/doc/manuals/maint-guide/... and I keep referring to it.

Even choosing the tool is not that easy...
I've settled on using git-buildpackage (to manage the source code dedicated to debian packaging stuff) with sbuild (to make the build reproducible).

Since your runtime seems to be python, i can hint you at how we package stuff in the Software Heritage team. We are orchestrating the build from the setup.py script file and using sbuild to make sure it's reproducible.

Concrete example on how we do it with a similar runtime to yours (or so i think):
- setup.py: https://forge.softwareheritage.org/diffusion/DSTO/browse/master/setup.py
this, you can compare with your own.

- debian folder: https://forge.softwareheritage.org/diffusion/DSTO/browse/master/debian/
That's the main folder which contains the debian packaging metadata (control and rules are the most important).
- make-package: This is the script that orchestrates the build https://forge.softwareheritage.org/diffusion/DENV/browse/master/bin/make-package;8234f8630455fe1e22bf3074f59c3f5e6d28aac5$50
(50-66 are the lines you want to take a look at).

> Can i find you on irc?

I'm ardumont there as well.

Hope this helps.

Cheers,

**Comment by pombredanne** [comment]
Thank ++ that's very helpful!
